[project]
name = "hushmark-api"
version = "0.1.0"
description = "Privacy-focused PII detection API for HushMark"
readme = "README.md"
authors = [
    { name = "Nilanjan Mandal", email = "nilanjanmandal15@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "en-core-web-lg @ https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.8.0/en_core_web_lg-3.8.0-py3-none-any.whl",
    "fastapi[standard]>=0.141.1",
    "presidio-analyzer>=2.2.364",
]

[project.scripts]
hushmark-api = "hushmark_api.main:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
